### ISSUE TITLE
Completely broke on Debian

### ISSUE THREAD

**Issue by mabushey** [joelandman/influxdbcli#1]
Anyway this could be made to work on Debian Linux?

make INSTPATH=/usr/local/bin

....
make: **\* [LeakTrace.o] Error 127
  GFUJI/Test-LeakTrace-0.15.tar.gz
  /usr/bin/make -- NOT OK
Makefile:22: recipe for target 'deps' failed
make: **\* [deps] Error 1

**Comment by joelandman** [comment]
Could you tell me which debian you used?  We develop it on wheezy, so it 
should work.

Also, could you provide more of the error output?  Or is that it?

If you are trying to write into a protected directory you would need a sudo 
in front.
Joe Landman
c: +1 734 612 4615
t: @sijoe

please pardon brevity and typos
sent from mobile device

**Comment by mabushey** [comment]
Hi Joe, thanks for the response. :)

I use testing. No idea what toy story of the month club that is.

# uname -a

Linux l01 3.19.1-x86_64-linode53 #1 SMP Tue Mar 10 15:30:28 EDT 2015 x86_64
GNU/Linux

Here's a ridiculous error in the perl Makefile: This distribution requires
a working compiler at Makefile.PL line 52.

root@l01:~/source/influxdbcli# make INSTPATH=/usr/local/bin
/usr/bin/sudo cpan Term::ReadLine Term::ReadLine::Gnu Text::ASCIITable
Getopt::Lucid JSON::PP LWP::UserAgent URI::Escape POSIX IO::File
Time::HiRes Moose List::MoreUtils
Reading '/root/.cpan/Metadata'
  Database was generated on Thu, 16 Apr 2015 20:41:02 GMT
Term::ReadLine is up to date (1.14).
Running install for module 'Term::ReadLine::Gnu'
Checksum for
/root/.cpan/sources/authors/id/H/HA/HAYASHI/Term-ReadLine-Gnu-1.26.tar.gz ok
'YAML' not installed, will not store persistent state
Configuring H/HA/HAYASHI/Term-ReadLine-Gnu-1.26.tar.gz with Makefile.PL
Could not find neither libtermcap.a, libncurses.a, or libcurses.
Warning: No success on command[/usr/bin/perl Makefile.PL INSTALLDIRS=site]
  HAYASHI/Term-ReadLine-Gnu-1.26.tar.gz
  /usr/bin/perl Makefile.PL INSTALLDIRS=site -- NOT OK
Text::ASCIITable is up to date (0.20).
Getopt::Lucid is up to date (1.05).
JSON::PP is up to date (2.27300).
LWP::UserAgent is up to date (6.13).
URI::Escape is up to date (3.31).
POSIX is up to date (1.38_03).
IO::File is up to date (1.16).
Time::HiRes is up to date (1.9726).
Running install for module 'Moose'
Checksum for /root/.cpan/sources/authors/id/E/ET/ETHER/Moose-2.1404.tar.gz
ok
Configuring E/ET/ETHER/Moose-2.1404.tar.gz with Makefile.PL
This distribution requires a working compiler at Makefile.PL line 52.
Warning: No success on command[/usr/bin/perl Makefile.PL INSTALLDIRS=site]
  ETHER/Moose-2.1404.tar.gz
  /usr/bin/perl Makefile.PL INSTALLDIRS=site -- NOT OK
Running install for module 'List::MoreUtils'
Checksum for
/root/.cpan/sources/authors/id/R/RE/REHSACK/List-MoreUtils-0.410.tar.gz ok
Configuring R/RE/REHSACK/List-MoreUtils-0.410.tar.gz with Makefile.PL
Checking whether pureperl is required... no
Checking for cc...
Variant providers in LMU::TestVariants: CanXS
Checking whether pureperl is required... (cached) no
Writing gt/Default/Functions.t
Writing gt/Default/Import.t
Writing gt/Default/XS.t
Writing gt/Default/ab.t
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for List::MoreUtils
Writing MYMETA.yml and MYMETA.json
  REHSACK/List-MoreUtils-0.410.tar.gz
  /usr/bin/perl Makefile.PL INSTALLDIRS=site -- OK
Running make for R/RE/REHSACK/List-MoreUtils-0.410.tar.gz
---- Unsatisfied dependencies detected during ----
----    REHSACK/List-MoreUtils-0.410.tar.gz   ----
    Test::LeakTrace [build_requires,optional]
cp lib/List/MoreUtils/XS.pm blib/lib/List/MoreUtils/XS.pm
cp lib/List/MoreUtils.pm blib/lib/List/MoreUtils.pm
cp lib/List/MoreUtils/PP.pm blib/lib/List/MoreUtils/PP.pm
Running Mkbootstrap for List::MoreUtils ()
chmod 644 MoreUtils.bs
/usr/bin/perl /usr/share/perl/5.20/ExtUtils/xsubpp  -typemap
/usr/share/perl/5.20/ExtUtils/typemap  MoreUtils.xs > MoreUtils.xsc && mv
MoreUtils.xsc MoreUtils.c
cc -c   -D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fwrapv -fno-strict-aliasing
-pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2
-g   -DVERSION=\"0.410\" -DXS_VERSION=\"0.410\" -fPIC "
-I/usr/lib/x86_64-linux-gnu/perl/5.20/CORE"   MoreUtils.c
/bin/sh: 1: cc: not found
Makefile:344: recipe for target 'MoreUtils.o' failed
make: **\* [MoreUtils.o] Error 127
  REHSACK/List-MoreUtils-0.410.tar.gz
  /usr/bin/make -- NOT OK
Running install for module 'Test::LeakTrace'
Checksum for
/root/.cpan/sources/authors/id/G/GF/GFUJI/Test-LeakTrace-0.15.tar.gz ok
Configuring G/GF/GFUJI/Test-LeakTrace-0.15.tar.gz with Makefile.PL
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for Test::LeakTrace
Writing MYMETA.yml and MYMETA.json
  GFUJI/Test-LeakTrace-0.15.tar.gz
  /usr/bin/perl Makefile.PL INSTALLDIRS=site -- OK
Running make for G/GF/GFUJI/Test-LeakTrace-0.15.tar.gz
cp lib/Test/LeakTrace.pm blib/lib/Test/LeakTrace.pm
cp lib/Test/LeakTrace/JA.pod blib/lib/Test/LeakTrace/JA.pod
cp lib/Test/LeakTrace/Script.pm blib/lib/Test/LeakTrace/Script.pm
Running Mkbootstrap for Test::LeakTrace ()
chmod 644 LeakTrace.bs
/usr/bin/perl "-Iinc" /usr/share/perl/5.20/ExtUtils/xsubpp  -typemap
/usr/share/perl/5.20/ExtUtils/typemap  LeakTrace.xs > LeakTrace.xsc && mv
LeakTrace.xsc LeakTrace.c
cc -c   -D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fwrapv -fno-strict-aliasing
-pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2
-g   -DVERSION=\"0.15\" -DXS_VERSION=\"0.15\" -fPIC "-I
/usr/lib/x86_64-linux-gnu/perl/5.20/CORE"   LeakTrace.c
/bin/sh: 1: cc: not found
Makefile:346: recipe for target 'LeakTrace.o' failed
make: **\* [LeakTrace.o] Error 127
  GFUJI/Test-LeakTrace-0.15.tar.gz
  /usr/bin/make -- NOT OK
Makefile:22: recipe for target 'deps' failed
make: **\* [deps] Error 1

**Comment by joelandman** [comment]
Interesting.  It couldn't find cc:

"usr/share/perl/5.20/ExtUtils/typemap  MoreUtils.xs > MoreUtils.xsc && mv
MoreUtils.xsc MoreUtils.c
cc -c   -D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fwrapv -fno-strict-aliasing
-pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2
-g   -DVERSION=\"0.410\" -DXS_VERSION=\"0.410\" -fPIC "
-I/usr/lib/x86_64-linux-gnu/perl/5.20/CORE"   MoreUtils.c
/bin/sh: 1: cc: not found
Makefile:344: recipe for target 'MoreUtils.o' failed"

Have you done an 'apt-get install build-essential' to install the base compiler/dev environment?  I think I had made the assumption this was done.  If its there, and you can execute cc/gcc by hand, there might be some other issue that I need to look at.

Please try a quick 'gcc --version' and 'cc --version' .  If you don't see those, please let me know.  I'll see if I can include a test for this in the makefile.

**Comment by joelandman** [comment]
I've not seen a response in almost 21 months, and our friends at InfluxDB, now InfluxData, have written their own CLI tool.  So this tool is deprecated.   I'll likely repurpose it later for other things, but I am closing this report for now.  Please re-open if you are interested in helping to diagnose what is the issue.  Future versions of this will likely come as a container with all dependencies baked in to simplify deployment.
